
version: 2

models:
  - name: users
    config:
      materialized: table
  - name: movies
    config:
      materialized: table
  - name: scores
    config:
      materialized: table
  - name: scores_users_movies
    config:
      materialized: table

sources: 
  - name: recomender_system_raw
    description: "machine learning raw tables"
    database: mlops
    schema: source
    tables:
      - name: scores_raw
        meta:
          dagster:
            asset_key: ["scores_raw"]
      - name: movies_raw
        meta:
          dagster:
            asset_key: ["movies_raw"]
      - name: users_raw
        meta:
          dagster:
            asset_key: ["users_raw"]