
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  - name: users
    config:
      materialized: table


sources: 
  - name: recomender_system_raw
    description: "machine learning raw tables"
    database: mlops
    schema: source
    tables:
      - name: scores
      - name: movies
      - name: users